### ISSUE TITLE
Human review required evaluation in Lab 3

### ISSUE THREAD

**Issue by rizasaputra** [donnieprakoso/workshop-eventDrivenMicroservices#1]
There are some issues with evaluation rule for "human review required" in Lab 3.

To forward the state to manual human review approval, the condition should be checking that `humanReviewRequired` from either of the inputs is true. In current definition, if we pass input like this it will result in Execution failed:
```
{
  "name": "Scenario 4",
  "document": true,
  "address": false,
  "amount": 1000
}
```
This issue is seen on work folder https://github.com/donnieprakoso/workshop-eventDrivenMicroservices/blob/ed93b5724574bdc2b3c6181df62aebab8273661b/3-lab-orchestrateMicroservices/work/cdk/app.py#L97 and source folder https://github.com/donnieprakoso/workshop-eventDrivenMicroservices/blob/ed93b5724574bdc2b3c6181df62aebab8273661b/3-lab-orchestrateMicroservices/source/cdk/app.py#L102

To forward the state to auto approval, the condition should be checking that `humanReviewRequired` from both inputs are false. The condition evaluation in source folder is correct, but the one in the work folder is not https://github.com/donnieprakoso/workshop-eventDrivenMicroservices/blob/ed93b5724574bdc2b3c6181df62aebab8273661b/3-lab-orchestrateMicroservices/work/cdk/app.py#L91

**Comment by donnieprakoso** [comment]
Thanks for pointing out these 2 issues. I'm going to review your PR.
